# Generated by Django 5.2.6 on 2025-10-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='brand_photos/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'photo'), name='unique_brands')],
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='unique_characteristics')],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='main_category_photos/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'photo'), name='unique_main_category')],
            },
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='secondary_category_photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_category', to='main_app.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='TripleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='triple_category_photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triple_category', to='main_app.secondarycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='main_app.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='main_app.triplecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_category_characteristics', to='main_app.characteristics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_category_characteristics', to='main_app.triplecategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category_brands', to='main_app.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_category_brands', to='main_app.triplecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='product_photos/')),
                ('photo_url', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='main_app.products')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'photo', 'photo_url'), name='unique_product_photos')],
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_characteristics', to='main_app.characteristics')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristics', to='main_app.products')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'characteristic', 'value'), name='unique_product_characteristics')],
            },
        ),
        migrations.CreateModel(
            name='Product3DModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_model', models.FileField(null=True, upload_to='product_3dmodels/')),
                ('file_model_url', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_3dmodels', to='main_app.products')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'file_model', 'file_model_url'), name='unique_product_3dmodels')],
            },
        ),
        migrations.CreateModel(
            name='ProductVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='product_videos/')),
                ('video_url', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='main_app.products')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'video', 'video_url'), name='unique_product_videos')],
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promo_photo', models.ImageField(upload_to='promo_photos/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='main_app.products')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'name', 'promo_photo'), name='unique_product_promotions')],
            },
        ),
        migrations.AddConstraint(
            model_name='secondarycategory',
            constraint=models.UniqueConstraint(fields=('category', 'name', 'photo'), name='unique_secondary_category'),
        ),
        migrations.AddConstraint(
            model_name='triplecategory',
            constraint=models.UniqueConstraint(fields=('category', 'name', 'photo'), name='unique_triple_category'),
        ),
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(fields=('category', 'brand', 'name'), name='unique_products'),
        ),
        migrations.AddConstraint(
            model_name='categorycharacteristics',
            constraint=models.UniqueConstraint(fields=('category', 'characteristic'), name='unique_category_characteristics'),
        ),
        migrations.AddConstraint(
            model_name='categorybrands',
            constraint=models.UniqueConstraint(fields=('category', 'brand'), name='unique_category_brands'),
        ),
    ]
