# Generated by Django 5.2.6 on 2025-12-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_productcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomments',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcomments',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
